name: ai-mammo-app
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - sqlalchemy
  - psycopg2
  - pydicom
  - SimpleITK
  - scikit-learn
  - pytorch
  - torchvision
  - pillow
  - numpy
  - pandas
  - pip
  - pip:
    - python-jose
    - python-multipart
    - pdf2image
    - python-decouple
    - passlib
    - python-dotenv
    - alembic
    - email-validator 